version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    depends_on:
      - random0
      - random1
      - random2
    links:
      - random0
      - random1
      - random2
    volumes:
      - ./prometheus/conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/conf/prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml

  random0:
    build: ./random-scraper
    image: random:latest
    ports:
      - "8080:8080"
    entrypoint:
      - /go/bin/random 
      - -listen-address=:8080

  random1:
    build: ./random-scraper
    image: random:latest
    ports:
      - "8081:8081"
    entrypoint:
      - /go/bin/random 
      - -listen-address=:8081

  random2:
    build: ./random-scraper
    image: random:latest
    ports:
      - "8082:8082"
    entrypoint:
      - /go/bin/random 
      - -listen-address=:8082